### ISSUE TITLE
Monitor fees yet to be collected

### ISSUE THREAD

**Issue by marczeller** [sakulstra/aavewatch#2]
every `borrow()` call create a fee of 0,25% of the _amount borrowed.

listening to borrow() events, subtracting the fees already collected by `repay()` calls and adding the fees of `flashloans()`

Can provide a clear picture of fees collected by the protocol and how much LEND will eventually be burnt.

**Comment by sakulstra** [comment]
will look into this soon™
I feel like it's unreasonable to do this on the client side of this client side only application so i'll need to add some server side caching layer first :sweat_smile:

**Comment by sakulstra** [comment]
@marczeller , was just looking into this and am wondering why
> subtracting the fees already collected by repay() calls

is needed :thinking: 

From the faq:
> The platform has 2 type of fees. From borrowers, a 0.25% of the loan amount is collected on loan origination, from which 20% is used for referral integrators and 80% is swapped to LEND token and burned. From flash loans, a 0.35% is collected from the loan amount, from which 70% is redirected as extra income for depositors of the protocol and 30% is splitted using the same 20%/80% model of the origination fee. There also exist transaction fees related with the Ethereum Blockchain usage, these fees depend on the network status and transaction complexity.

So shouldn't it be enough to `SUM(borrows)*0.25%*80%+SUM(flashLoans)*0.35%*30%*80%` to get the total amount of fees(to be) collected by aave to burn lend?
